name: Playwright Tests in safari
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  safari:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests in safari
      run: PLAYWRIGHT_JUNIT_OUTPUT_NAME=reports/report.xml npx playwright test --project=webkit  --reporter=junit
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: reports/
        retention-days: 30
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '/reports/report.xml'